name: Build and deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
          
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          version: 10
          run_install: true
          
      - name: Build Next.js project
        run: pnpm run build
        
      - name: Tailscale
        uses: tailscale/github-action@v3
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:ci

      - name: send project files
        run: rsync -avz --delete -e "ssh -o StrictHostKeyChecking=no" .next public package.json pnpm-lock.yaml pi@raspberrypi:~/bohem-consulting/hackathon-lite-sandvika
        
      - name: install remote npm packages
        run: ssh -o StrictHostKeyChecking=no pi@raspberrypi "bash -c 'cd ~/bohem-consulting/hackathon-lite-sandvika && /home/pi/.npm-global/bin/pnpm install'"

      - name: deploy supabase key secret 
        run: ssh -o StrictHostKeyChecking=no pi@raspberrypi "bash -c 'cd ~/bohem-consulting/hackathon-lite-sandvika && echo NEXT_PUBLIC_SUPABASE_ANON_KEY=$SUPABASE_KEY > .env.local'"
        env:
          SUPABASE_KEY: ${{secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY}}}
          
      - name: deploy supabase url secret 
        run: ssh -o StrictHostKeyChecking=no pi@raspberrypi "bash -c 'cd ~/bohem-consulting/hackathon-lite-sandvika && echo NEXT_PUBLIC_SUPABASE_URL=$SUPABASE_URL >> .env.local'"
        env:
          SUPABASE_URL: ${{secrets.NEXT_PUBLIC_SUPABASE_URL}}
      
      - name: deploy supabase service role secret
        run: ssh -o StrictHostKeyChecking=no pi@raspberrypi "bash -c 'cd ~/bohem-consulting/hackathon-lite-sandvika && echo SUPABASE_SERVICE_ROLE=$SUPABASE_SECRET >> .env.local'"
        env:
          SUPABASE_SECRET: ${{secrets.SUPABASE_SERVICE_ROLE}}

      - name: deploy aws access key id
        run: ssh -o StrictHostKeyChecking=no pi@raspberrypi "bash -c 'cd ~/bohem-consulting/hackathon-lite-sandvika && echo AWS_ACCESS_KEY_ID=$AWS_ACCES_KEY_ID >> .env.local'"
        env:
          AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
          
      - name: deploy aws secret
        run: ssh -o StrictHostKeyChecking=no pi@raspberrypi "bash -c 'cd ~/bohem-consulting/hackathon-lite-sandvika && echo AWS_SECRET=$AWS_SECRET >> .env.local'"
        env:
          AWS_SECRET: ${{secrets.AWS_SECRET}}

      - name: deploy aws ses mail identity
        run: ssh -o StrictHostKeyChecking=no pi@raspberrypi "bash -c 'cd ~/bohem-consulting/hackathon-lite-sandvika && echo SES_SENDER_MAIL=$SES_SENDER_MAIL >> .env.local'"
        env:
          SES_SENDER_MAIL: "no-reply@hackathonlite.no"
          
      - name: restart pm2
        run: ssh -o StrictHostKeyChecking=no pi@raspberrypi "bash -c '/home/pi/.local/share/pnpm/pm2 restart hackathon-lite'"
